In [9]:
# Part 1: NumPy Array Operations
import numpy as np

# 1. Create a 1D NumPy array
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

# 2. Inspection and properties
print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Shape: (7,)
Data type: float64
Number of elements: 7


In [2]:
# 3. Array Operations
temperatures_f = (temperatures_w1 * 9/5) + 32
print("Fahrenheit:", temperatures_f)

print("Maximum:", temperatures_w1.max())
print("Minimum:", temperatures_w1.min())
print("Mean:", temperatures_w1.mean())

# 4. Slicing and Indexing
print("First three days:", temperatures_w1[:3])
print("Weekend (last two days):", temperatures_w1[-2:])
print("Middle three days:", temperatures_w1[2:5])

Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum: 26.1
Minimum: 20.8
Mean: 23.542857142857144
First three days: [22.5 25.3 20.8]
Weekend (last two days): [24.8 21.9]
Middle three days: [20.8 23.4 26.1]


In [3]:
# 5. Create a 2D array
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],   # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]    # Week 2
])
print(temperatures)

# 6. Inspect the 2D array
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

# Slicing
print("Week 1:", temperatures[0])
print("Week 2:", temperatures[1])
print("Weekend of both weeks:")
print(temperatures[:, -2:])

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]
Shape: (2, 7)
Data type: float64
Total number of elements: 14
Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekend of both weeks:
[[24.8 21.9]
 [22.8 20.1]]


In [5]:
# Part 2: Pandas Series
import pandas as pd

# 1. Creating a Pandas Series
marks = pd.Series([95, 92, 89, 85, 80],
                  index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

# 2. Indexing and Slicing
print("1st rank student:", marks.iloc[0])
print("Top 3 ranks:")
print(marks.loc['Rank1':'Rank3'])
print("3rd rank student:", marks.iloc[2])
print("Ranks with marks above 90:")
print(marks[marks > 90])

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64
1st rank student: 95
Top 3 ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64
3rd rank student: 89
Ranks with marks above 90:
Rank1    95
Rank2    92
dtype: int64


In [6]:
# 3. Manipulating Series

# Modify the mark of the 1st rank to 100
marks['Rank1'] = 100
print("After modifying Rank1:")
print(marks)

# Remove the entry for the last rank
marks = marks.drop('Rank5')
print("After removing Rank5:")
print(marks)

# Compute CGPA by dividing each mark by 10
cgpa = marks / 10
print("CGPA:")
print(cgpa)

After modifying Rank1:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
After removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [7]:
# Part 3: Pandas DataFrame
# 1. Creating the DataFrame
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West',
               'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

# 2. Data Exploration
print(transactions)

print("\nHead:")
print(transactions.head())

print("\nTail:")
print(transactions.tail())

print("\nShape:", transactions.shape)
print("Columns:", list(transactions.columns))
print("\nData types:")
print(transactions.dtypes)

print("\nInfo:")
transactions.info()

print("\nProductCategory and Amount only:")
print(transactions[['ProductCategory', 'Amount']])

print("\nLast 3 columns:")
print(transactions.iloc[:, -3:])

print("\nNorth region with Amount > 200:")
print(transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)])

print("\nValue counts of ProductCategory:")
print(transactions['ProductCategory'].value_counts())

print("\nUnique regions:")
print(transactions['Region'].unique())

print("\nMean amount by region:")
print(transactions.groupby('Region')['Amount'].mean())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Head:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Cl

In [8]:
# 3. Manipulating the DataFrame

# Modify the Amount for TransactionID 102 to 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print("After modifying TransactionID 102:")
print(transactions)

# Add a new column 'Discount' (10% of Amount)
transactions['Discount'] = transactions['Amount'] * 0.10
print("\nAfter adding Discount:")
print(transactions)

# Remove the row with TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]
print("\nAfter removing TransactionID 109:")
print(transactions)

# Delete the 'Discount' column
transactions = transactions.drop(columns=['Discount'])
print("\nAfter deleting Discount column:")
print(transactions)

After modifying TransactionID 102:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

After adding Discount:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6      